<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Hassan-PC" name="WordpressQA.SignUpErrorHandling" tests="2" failures="1" timestamp="19 Oct 2018 12:06:34 GMT" time="54.648" errors="0">
  <testcase name="InvalidEmail" time="54.648" classname="WordpressQA.SignUpErrorHandling">
    <failure type="java.lang.AssertionError" message="expected [Looks like something went wrong
Email address is not valid
Password is not valid
Read Terms and Privacy Policy not checked] but found [Looks like something went wrong
Email address is not valid
Password is not valid
Read Terms and Privacy Policy not checked]">
      <![CDATA[java.lang.AssertionError: expected [Looks like something went wrong
Email address is not valid
Password is not valid
Read Terms and Privacy Policy not checked] but found [Looks like something went wrong
Email address is not valid
Password is not valid
Read Terms and Privacy Policy not checked]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at WordpressQA.SignUpErrorHandling.InvalidEmail(SignUpErrorHandling.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- InvalidEmail -->
  <testcase name="PasswordNotMatch" classname="WordpressQA.SignUpErrorHandling">
    <skipped/>
  </testcase> <!-- PasswordNotMatch -->
</testsuite> <!-- WordpressQA.SignUpErrorHandling -->
