<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="10" hostname="Hassan-PC" failures="1" tests="1" name="Default test" time="31.143" errors="0" timestamp="14 Sep 2018 16:16:34 GMT">
  <testcase classname="mm.UnauthenticatedHomePage" name="signupE4" time="22.237">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at mm.UnauthenticatedHomePage.signupE4(UnauthenticatedHomePage.java:711)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- signupE4 -->
  <testcase classname="mm.UnauthenticatedHomePage" name="cancel" time="0.0">
    <ignored/>
  </testcase> <!-- cancel -->
  <testcase classname="mm.UnauthenticatedHomePage" name="Shop" time="0.0">
    <ignored/>
  </testcase> <!-- Shop -->
  <testcase classname="mm.UnauthenticatedHomePage" name="Men" time="0.0">
    <ignored/>
  </testcase> <!-- Men -->
  <testcase classname="mm.UnauthenticatedHomePage" name="Signin" time="0.0">
    <ignored/>
  </testcase> <!-- Signin -->
  <testcase classname="mm.UnauthenticatedHomePage" name="signupE1" time="0.0">
    <ignored/>
  </testcase> <!-- signupE1 -->
  <testcase classname="mm.UnauthenticatedHomePage" name="signupE3" time="0.0">
    <ignored/>
  </testcase> <!-- signupE3 -->
  <testcase classname="mm.UnauthenticatedHomePage" name="ForgotPassword" time="0.0">
    <ignored/>
  </testcase> <!-- ForgotPassword -->
  <testcase classname="mm.UnauthenticatedHomePage" name="signupE2" time="0.0">
    <ignored/>
  </testcase> <!-- signupE2 -->
  <testcase classname="mm.UnauthenticatedHomePage" name="Contactus" time="0.0">
    <ignored/>
  </testcase> <!-- Contactus -->
  <testcase classname="mm.UnauthenticatedHomePage" name="women" time="0.0">
    <ignored/>
  </testcase> <!-- women -->
</testsuite> <!-- Default test -->
