<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="11" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-09-14T16:16:03Z" name="Default suite" finished-at="2018-09-14T16:16:34Z" duration-ms="31143">
    <groups>
    </groups>
    <test started-at="2018-09-14T16:16:03Z" name="Default test" finished-at="2018-09-14T16:16:34Z" duration-ms="31143">
      <class name="mm.UnauthenticatedHomePage">
        <test-method is-config="true" signature="setup()[pri:0, instance:mm.UnauthenticatedHomePage@1e178745]" started-at="2018-09-14T16:16:03Z" name="setup" finished-at="2018-09-14T16:16:11Z" duration-ms="8547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="signupE4()[pri:10, instance:mm.UnauthenticatedHomePage@1e178745]" started-at="2018-09-14T16:16:11Z" name="signupE4" finished-at="2018-09-14T16:16:34Z" duration-ms="22237" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at mm.UnauthenticatedHomePage.signupE4(UnauthenticatedHomePage.java:711)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signupE4 -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:mm.UnauthenticatedHomePage@1e178745]" started-at="2018-09-14T16:16:34Z" name="teardown" finished-at="2018-09-14T16:16:34Z" duration-ms="328" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signupE4 status=FAILURE method=UnauthenticatedHomePage.signupE4()[pri:10, instance:mm.UnauthenticatedHomePage@1e178745] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- mm.UnauthenticatedHomePage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
